INSERT INTO Faculty (`FacultyID`, `Name`, `Salary`) VALUES (0, 'Lfwat Cywqdr', 53967);
INSERT INTO Faculty (`FacultyID`, `Name`, `Salary`) VALUES (1, 'Ct Yubgk', 61469);
INSERT INTO Faculty (`FacultyID`, `Name`, `Salary`) VALUES (5, 'Ldqth Fc', 78446);
INSERT INTO Faculty (`FacultyID`, `Name`, `Salary`) VALUES (35, 'Qwh Avg', 72348);
INSERT INTO Faculty (`FacultyID`, `Name`, `Salary`) VALUES (36, 'Qkavcj Xqi', 58483);
INSERT INTO Student (`UIN`, `Name`, `Major`, `Advisor`) VALUES (16551, 'Pu Kmv', 'MXMU', 2131);
INSERT INTO Student (`UIN`, `Name`, `Major`, `Advisor`) VALUES (16552, 'Erg Zlzyl', 'JZVL', 62);
INSERT INTO Student (`UIN`, `Name`, `Major`, `Advisor`) VALUES (16553, 'Mlixd Ucun', 'KNTV', 538);
INSERT INTO Student (`UIN`, `Name`, `Major`, `Advisor`) VALUES (16554, 'Bzee Crfvlo', 'XDMX', 1296);
INSERT INTO Student (`UIN`, `Name`, `Major`, `Advisor`) VALUES (16569, 'Bl Vtte', 'TUDV', 1574);
INSERT INTO Student (`UIN`, `Name`, `Major`, `Advisor`) VALUES (16570, 'Sy Wyhu', 'GKOC', 858);
INSERT INTO Student (`UIN`, `Name`, `Major`, `Advisor`) VALUES (16571, 'Uoxvy Bnsqktsavw', 'ATSN', 965);
INSERT INTO StudentOrganization (`StudentOrganizationID`, `Name`, `Category`) VALUES (10, 'Togb', 'Zfakm');
INSERT INTO StudentOrganization (`StudentOrganizationID`, `Name`, `Category`) VALUES (11, 'Wymlprnaadwy', 'N');
INSERT INTO StudentOrganization (`StudentOrganizationID`, `Name`, `Category`) VALUES (12, 'Baflqzu', 'A');
INSERT INTO StudentOrganization (`StudentOrganizationID`, `Name`, `Category`) VALUES (13, 'Delckhjnhhj', 'Jy');
INSERT INTO StudentOrganization (`StudentOrganizationID`, `Name`, `Category`) VALUES (14, 'Ccccblinizgexwefz', 'Yjgcb');
INSERT INTO StudentOrganization (`StudentOrganizationID`, `Name`, `Category`) VALUES (627, 'Jjj', 'Vur');
INSERT INTO Course (`Subject`, `CourseNumber`, `Hours`, `Title`) VALUES ('ECIJ', 326, 1, 'Uidtdmolimbg of Dvvtuigiuter');
INSERT INTO Course (`Subject`, `CourseNumber`, `Hours`, `Title`) VALUES ('XAML', 777, 1, 'Xjljjekprch of Gbjihubfx');
INSERT INTO Course (`Subject`, `CourseNumber`, `Hours`, `Title`) VALUES ('ZLYS', 864, 3, 'Oclotl of Xrvjfdbzk');
INSERT INTO Course (`Subject`, `CourseNumber`, `Hours`, `Title`) VALUES ('QVLI', 721, 3, 'Ssyytiggkah of Ndk');
INSERT INTO Course (`Subject`, `CourseNumber`, `Hours`, `Title`) VALUES ('ZHEA', 465, 3, 'Ksszy of Ynu');
INSERT INTO EnrolledIn (`Semester`, `ClassSubject`, `ClassNumber`, `UIN`, `Grade`) VALUES ('Fall', 'CBAX', 804, 2714, 'B');
INSERT INTO EnrolledIn (`Semester`, `ClassSubject`, `ClassNumber`, `UIN`, `Grade`) VALUES ('Summer II', 'QAFR', 753, 2714, 'C');
INSERT INTO EnrolledIn (`Semester`, `ClassSubject`, `ClassNumber`, `UIN`, `Grade`) VALUES ('Fall', 'SAUW', 813, 2714, 'B');
INSERT INTO EnrolledIn (`Semester`, `ClassSubject`, `ClassNumber`, `UIN`, `Grade`) VALUES ('Summer I', 'NKDT', 341, 2714, 'D');
INSERT INTO EnrolledIn (`Semester`, `ClassSubject`, `ClassNumber`, `UIN`, `Grade`) VALUES ('Spring', 'QTYS', 218, 16571, 'C');
INSERT INTO EnrolledIn (`Semester`, `ClassSubject`, `ClassNumber`, `UIN`, `Grade`) VALUES ('Summer II', 'VMTQ', 731, 16571, 'D');
INSERT INTO Teaches (`Subject`, `CourseNumber`, `FacultyID`, `Semester`) VALUES ('XXJU', 526, 0, 'Summer II');
INSERT INTO Teaches (`Subject`, `CourseNumber`, `FacultyID`, `Semester`) VALUES ('DXIJ', 698, 0, 'Fall');
INSERT INTO Teaches (`Subject`, `CourseNumber`, `FacultyID`, `Semester`) VALUES ('JNQA', 955, 2712, 'Summer I');
INSERT INTO Teaches (`Subject`, `CourseNumber`, `FacultyID`, `Semester`) VALUES ('TTEB', 424, 2713, 'Spring');
INSERT INTO Teaches (`Subject`, `CourseNumber`, `FacultyID`, `Semester`) VALUES ('ZHDH', 368, 2713, 'Summer II');
INSERT INTO Leads (`FacultyID`, `StudentOrganizationID`, `Joined`) VALUES (1659, 270, '10/2011');
INSERT INTO Leads (`FacultyID`, `StudentOrganizationID`, `Joined`) VALUES (1594, 467, '5/2008');
INSERT INTO Leads (`FacultyID`, `StudentOrganizationID`, `Joined`) VALUES (438, 267, '1/2011');
INSERT INTO Leads (`FacultyID`, `StudentOrganizationID`, `Joined`) VALUES (1813, 251, '5/2008');
INSERT INTO Leads (`FacultyID`, `StudentOrganizationID`, `Joined`) VALUES (758, 130, '7/2008');
INSERT INTO MemberOf (`UIN`, `StudentOrganizationID`, `Joined`) VALUES (2714, 301, '12/2011');
INSERT INTO MemberOf (`UIN`, `StudentOrganizationID`, `Joined`) VALUES (2715, 476, '1/2012');
INSERT INTO MemberOf (`UIN`, `StudentOrganizationID`, `Joined`) VALUES (2715, 620, '2/2009');
INSERT INTO MemberOf (`UIN`, `StudentOrganizationID`, `Joined`) VALUES (2715, 290, '2/2011');
INSERT INTO MemberOf (`UIN`, `StudentOrganizationID`, `Joined`) VALUES (2716, 63, '11/2009');
